# This is a basic workflow to help you get started with Actions

name: Website Update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: S3 Deploy
        uses: shallwefootball/upload-s3-action@v1.1.2
        with:
           # aws key id
          aws_key_id: ${{secrets.AWS_ACCESS_KEY_DEV}}
          # aws secret access key
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}
          # aws bucket name
          aws_bucket: scalato-website
          # directory to upload
          source_dir: ./website
